### ISSUE TITLE
Password being limited in size (128)

### ISSUE THREAD

**Issue by SkyDev125** [felddy/foundryvtt-docker#1002]
### Bug description

When running the docker container, it simply wasnt working with the username and password I had... the password was 128 characters in size, and had multiple different symbols, which were accepted by foundryVTT's standards, but not by the docker container.

### Steps to reproduce

Create a very large password
Try to use it in the container config

### Expected behavior

Log in succesfully

### Container metadata

```shell
no longer available (as I fixed it by changing the password)
```

### Relevant log output

```console
no longer available (as I fixed it by changing the password)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Thank you for reporting this bug.  In order to determine the cause of the issue I do need to know the version of the container and see the relevant log output which displays the error.  Please amend your description with this information.  

For this specific issue I also need to know how you were specifying the credentials for your account.  Were you passing them in via environment variables, or using the [container secrets](https://github.com/felddy/foundryvtt-docker?tab=readme-ov-file#using-secrets).  If you were using environment variables, were you passing them in [via the command line](https://github.com/felddy/foundryvtt-docker?tab=readme-ov-file#running-with-docker-and-credentials), or as part of a [`docker-compose.yml`](https://github.com/felddy/foundryvtt-docker?tab=readme-ov-file#configuration-management) file?
