### ISSUE TITLE
Support for 0.8.8 version.

### ISSUE THREAD

**Issue by bsas** [felddy/foundryvtt-docker#223]
# 🚀 Feature Proposal

Add support for FoundryVTT v0.8.8

See: https://foundryvtt.com/releases/0.8.8

**Comment by bsas** [comment]
.

**Comment by felddy** [comment]
This is already underway.
See branch: https://github.com/felddy/foundryvtt-docker/tree/release/0.8.8

Since there were new options added to `0.8.8` this is a bit more work than a simple version bump.  

* Custom TURN configs are back, but they are not configurable from `options.json`.  See clarification: https://gitlab.com/foundrynet/foundryvtt/-/issues/5406
* New "demo" mode feature added.  See: https://gitlab.com/foundrynet/foundryvtt/-/issues/2780

If you are feeling adventurous you can pull the image created by CI for the branch `felddy/foundryvtt:release-0.8.8` and get `0.8.8` running before I publish a completed release.

**Comment by bsas** [comment]
Nice! :D

**Comment by felddy** [comment]
This issue can stay open until it is completed.  It will auto-close when the PR is merged.
