### ISSUE TITLE
Websocket config?

### ISSUE THREAD

**Issue by MacDork** [felddy/foundryvtt-docker#43]
# 💬 Questions and Help
I can load foundry and use it just fine internally at http://localhost:30000/ , but when I try to connect to my internet facing hostname with letsencrypt cert all configured, using the Apache2 SSL Proxy config from [this page](https://foundryvtt.com/article/apache/), the setup page loads, but I can't login and keep getting this error in the browser console:

`Firefox can’t establish a connection to the server at wss://foundry.mydomain.com/socket.io/?session=<sessionid>&transport=websocket.`

(note the extra 's' in **wss** above)

My VirtualHost has this line (from the page above):

`ProxyPass             "/socket.io/" "ws*//<my foundry internal ip>:30000/socket.io/"`

Is it possible that there's a configuration in your container that is asking for a connection to **wss://** instead of **ws://**?  I'm at a loss and don't know how to proceed.

Apache Log, fwiw, says:
` [proxy:error] [pid 29863] (111)Connection refused: AH00957: HTTP: attempt to connect to <my foundry internal ip>:30000 (<internal ip again>) failed`

**Comment by felddy** [comment]
@MacDork,  that is frustrating.  There isn't anything in the container that is modifying the networking.  It's a pretty straightforward containerized node application , with some installation/authentication sauce on the front.

If you are connecting directly to Foundry without the proxy you will be using `http:` and `ws:`.  When the proxy is in place with TLS, you will be connecting using `https` and `wss`.  So seeing `wss` is normal in the mode you describe.

I think that Apache log message is the most telling.  It seems that your browser can talk to Apache, but Apache cannot reach port `30000`.   I read some of your chat messages in `#troubleshooting` where you were working on firewall configs.  I'm assuming that Apache and the Docker container are on the same machine.

Confirm with the container running that it is listening on all interfaces: 

```console
❱ netstat -an | grep 30000
tcp46      0      0  *.30000                *.*                    LISTEN     
```

Verify that you can connect to port 30000 on the same box: 

```console
wget -O - http://localhost:30000
```

It might be worth trying [`nginx`](https://www.nginx.com/) or [`caddy`](https://caddyserver.com/) as the proxy to rule out an Apache config error, or a firewall issue.  

I am working on a Docker composition with an included proxy since this is a very common deployment.  If the problem doesn't reveal itself by then, it might be a good solution.   I hope it is working for you before then.

**Comment by MacDork** [comment]
Ahh.   wss makes sense, now. 

I've got other services proxied behind Apache, so I don't think I can have another service (like nginx) listening on 443 (can I?), but the netstat *does* seem to show that it's not listening for ipv4.  

`tcp6       0      0 :::30000                :::*                    LISTEN`

Disabling ufw yields the same result, so I think the fw is out of the equation.  Do you have any other guidance that might help?

**Comment by felddy** [comment]
That is strange... we either need to get Docker listening on IPv4 or change your Apache config to use `::1`.  Take a look at this link for some ideas: 

https://stackoverflow.com/questions/29957143/make-docker-use-ipv4-for-port-binding

**Comment by MacDork** [comment]
Thanks for the help -- I don't think it's the container's fault.  wget works fine, and on my <internalip>:30000, i'm able to access foundry wonderfully.  I'm still running a Fantasy Grounds campaign, so it'll be a long while before I'm ready to fully make the move.  Thank you for your time, and for the tips, and for creating this container.  I'll probably continue to use it after I work out the socket issue.  If you'd like to close this out, please do.

**Comment by MacDork** [comment]
FWIW, I have the same issue w/ the Node install, and leave the Docker container off.

**Comment by felddy** [comment]
Wow.  Still happens with just Node?  I'd keep digging on those IPv6/IPv4 binding configurations.  

I'm glad you plan on using the container.  Let me know if you have any more questions either here or in Discord.  

Good luck!

**Comment by MacDork** [comment]
I got it working.

I needed to add a Rewrite to my Apache2 virtualhost settings:

```
  RewriteEngine          on
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule ^/socket.io/(.*)  ws://localhost:30000/socket.io/$1 [P,L]
  SSLProxyEngine         on

```
