### ISSUE TITLE
Unable to update lock within the stale threshold

### ISSUE THREAD

**Issue by MacDork** [felddy/foundryvtt-docker#92]
# 💬 Questions and Help
Mark --
First off; *thank you* for creating and maintaining this image.

I just updated to 0.7.5 and on my `docker-compose up`, the server hangs and I see:

```
foundry    | FoundryVTT | 2020-10-22 11:18:37 | [info] License verification succeeded
foundry    | FoundryVTT | 2020-10-22 11:18:37 | [info] Server started and listening on port 30000
foundry    | FoundryVTT | 2020-10-22 11:18:42 | [error] Unable to update lock within the stale threshold
foundry    | Error: Unable to update lock within the stale threshold
foundry    |     at /home/foundry/resources/app/node_modules/proper-lockfile/lib/lockfile.js:136:25
foundry    |     at /home/foundry/resources/app/node_modules/proper-lockfile/node_modules/graceful-fs/polyfills.js:285:20
foundry    |     at FSReqCallback.oncomplete (fs.js:169:5)

```

Of note -- my Foundry data is stored on a network mounted drive, and has worked properly for a while now, but it seems like it may be relevant here.  Help?

**Comment by felddy** [comment]
@MacDork, you're very welcome.  I enjoy keeping this container in shipshape.  This is my way of supporting the Foundry community.  Onto the locking issue...

This is most certainly related to the data store being on a network filesystem.   Searching the discord server for `stale threshold` shows people having this issue with USB sticks and the FAT filesystem.  It seems that another common cause for this is using backup services that modify the filesystem. e.g; OneDrive, DropBox, etc...

A few things I'd try:
 1. See if the issue persists if you revert back to the previous version that you were using.  You can do this in your `docker-compose.yml` file by specifying the version as a tag.  e.g.; `felddy/foundryvtt:0.6.6`  From what I've read on discord I expect this will not fix the issue.
 1. Create an empty store on the network filesystem and verify that the container works when that is mapped to the `/data` volume.  I expect that this will work.
 1. Are there any stale locks laying around?  If you're on a POSIX system try running `find your_data_dir -name '*.lock'`

The library that is upset is [proper-lockfile](https://www.npmjs.com/package/proper-lockfile).   Foundry `0.7.5` is using the latest version of that library `4.1.1`.   The error is being generated by this code: 

https://github.com/moxystudio/node-proper-lockfile/blob/2321190d6d954be8bd3eb9f1d8f9e6e50e180f4a/lib/lockfile.js#L131-L139

So, it seems that the library is unable to update the modification time of the lock within the threshold time.   It reads this as a compromised lock and throws an error.  Again this points at the network filesystem as being the culprit.

A few questions:

 - Could you provide some details about the configuration you're using?: Host OS, Network filesystem type.  
 - Does the lock error occur immediately, or did you take some action in the web interface?

I'm pretty sure we'll get this sorted out since it was working previously.  Also, since we're playing around with your `/data` directory make sure you've got a secured backup copy.  I don't want you to lose anything critical. 

Let me know what you find.

**Comment by MacDork** [comment]
Thanks Mark -- 
I restarted the storage host and it's working again.  I still saw the error when I booted the container up, but after waiting a while, the server finished loading.

I use a script to shut down each of my docker containers, then rsync `docker-compose.yml` + any data directories (I store my data in the same directory as the compose for ease of use), then start the container back up.  It works pretty well, and it generally runs in the middle of the night, but I think it's possible I had some other processes hitting the storage earlier.  

For the record -- ubuntu host + cifs mounted storage into my foundry directory.  I then use Arq to back the data up to Backblaze B2 at night.

Cheers!

**Comment by felddy** [comment]
Great!  I'm glad you were able to get it working.   Thanks for sharing the specifics of your setup.  It'll help the next person that encounters that lock issue.

I hope it is all smooth sailing for you from here. ⛵ 
If I can help you with anything else in the future please do not hesitate to contact me.
